# Generated by Django 6.0.5 on 2026-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0003_shopprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', '-date'], name='khata_trans_custome_4f4250_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='khata_trans_date_4fc4ce_idx'),
        ),
    ]
