# Generated by Django 6.0.5 on 2026-07-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0005_transaction_transaction_amount_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment_drive_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attachment_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attachment_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attachment_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
