# Generated by Django 6.0.5 on 2026-08-26 11:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0008_activationledgerentry_reversal_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment_drive_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('attachment_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfer_vouchers', to='khata.customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khata_transfer_vouchers', to=settings.AUTH_USER_MODEL)),
                ('to_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfer_vouchers', to='khata.customer')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='khata.transfervoucher'),
        ),
        migrations.AddIndex(
            model_name='transfervoucher',
            index=models.Index(fields=['owner', '-date'], name='khata_trans_owner_i_283881_idx'),
        ),
        migrations.AddConstraint(
            model_name='transfervoucher',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transfer_voucher_amount_positive'),
        ),
    ]
