# Generated by Django 6.0.5 on 2026-09-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0010_activationoperatorsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationoperatorsettings',
            name='show_coupons',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activationoperatorsettings',
            name='show_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activationoperatorsettings',
            name='show_downloads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activationoperatorsettings',
            name='show_erp_licenses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activationoperatorsettings',
            name='show_khata',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activationoperatorsettings',
            name='show_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activationoperatorsettings',
            name='show_user_licenses',
            field=models.BooleanField(default=True),
        ),
    ]
