# Generated by Django 6.0.5 on 2026-10-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0011_activationoperatorsettings_show_coupons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationoperatorsettings',
            name='fixed_activation_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Set amount to lock this operator’s User License and ERP activation amount. Leave blank to allow entry.', null=True),
        ),
    ]
