# Generated by Django 6.0.5 on 2026-10-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0012_activationoperatorsettings_fixed_activation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_bad_debt',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
