# Generated by Django 4.2 on 2026-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedownload', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlink',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='downloadlink',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Software', 'Software'), ('Utility', 'Utility'), ('Driver', 'Driver'), ('Game', 'Game'), ('Other', 'Other')], default='General', max_length=50),
        ),
    ]
