# Generated by Django 6.0.5 on 2026-08-11 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onedownload', '0005_remove_downloadlink_and_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadCatalogSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('catalog', models.JSONField(default=dict)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('category_count', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('synced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_catalog_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download catalog snapshot',
                'verbose_name_plural': 'Download catalog snapshot',
            },
        ),
    ]
