# Generated by Django 6.0.5 on 2026-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_used_by_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(db_column='CouponCode', max_length=40, unique=True),
        ),
    ]
