# Generated by Django 6.0.5 on 2026-07-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(db_column='CouponCode', max_length=48, unique=True),
        ),
    ]
