# Generated by Django 6.0.5 on 2026-07-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_task_reminders_t_status_67fff1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='linked_erp',
        ),
        migrations.RemoveField(
            model_name='task',
            name='linked_pacs',
        ),
    ]
