# Generated by Django 6.0.5 on 2026-05-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientlicense',
            options={'managed': False},
        ),
    ]
