# Generated by Django 6.0.5 on 2026-05-17 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_alter_clientlicense_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientlicense',
            table='nclData',
        ),
    ]
