# Generated by Django 6.0.5 on 2026-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_alter_clientlicense_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pacs_name', models.CharField(blank=True, db_column='PacsName', max_length=255, null=True)),
                ('dist', models.CharField(blank=True, db_column='Dist', max_length=100, null=True)),
                ('f_year', models.CharField(blank=True, db_column='fYear', max_length=20, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='isActive', default=0, null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', default=0, null=True)),
                ('payment_status', models.IntegerField(blank=True, db_column='PaymentStatus', null=True)),
                ('operator_mobile', models.BigIntegerField(blank=True, db_column='OperatorMobile', null=True)),
                ('mobile', models.BigIntegerField(blank=True, db_column='Mobile', null=True)),
                ('accepte_by', models.TextField(blank=True, db_column='AccepteBy', null=True)),
                ('brach', models.CharField(blank=True, db_column='Brach', max_length=100, null=True)),
                ('branch_approve', models.IntegerField(blank=True, db_column='BranchApprove', null=True)),
                ('branch_id', models.CharField(blank=True, db_column='BranchID', max_length=50, null=True)),
                ('branch_pass', models.CharField(blank=True, db_column='BranchPass', max_length=50, null=True)),
                ('date_time', models.DateTimeField(blank=True, db_column='Date_Time', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='lastLogin', null=True)),
                ('entry_count', models.IntegerField(blank=True, db_column='EntryCount', null=True)),
                ('for_whys', models.CharField(blank=True, db_column='forWhys', max_length=255, null=True)),
                ('is_animal', models.IntegerField(blank=True, db_column='IsAnimal', null=True)),
                ('is_pri', models.CharField(blank=True, db_column='IsPri', max_length=10, null=True)),
                ('limit_of_entrys', models.IntegerField(blank=True, db_column='LimitOfEntrys', default=20, null=True)),
                ('system_id', models.CharField(blank=True, db_column='systemID', max_length=100, null=True)),
                ('u_pass', models.CharField(blank=True, db_column='uPass', max_length=100, null=True)),
                ('utr_number', models.CharField(blank=True, db_column='UtrNumber', max_length=100, null=True)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
