# Generated by Django 6.0.5 on 2026-05-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_userinfodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblPacsErp',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', default=0, null=True)),
                ('brach', models.CharField(blank=True, db_column='Brach', max_length=255, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True, db_column='Date_Time', null=True)),
                ('dist', models.CharField(blank=True, db_column='Dist', max_length=255, null=True)),
                ('erp_id', models.TextField(blank=True, db_column='ErpID', null=True)),
                ('expiry_date', models.DateField(blank=True, db_column='Expiry_Date', null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='isActive', default=0, null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='lastLogin', null=True)),
                ('operator_mobile', models.BigIntegerField(blank=True, db_column='OperatorMobile', null=True)),
                ('pacs_name', models.CharField(blank=True, db_column='PacsName', max_length=255, null=True)),
                ('payment_status', models.IntegerField(blank=True, db_column='PaymentStatus', default=0, null=True)),
                ('remark', models.CharField(blank=True, db_column='Remark', max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=255, null=True)),
                ('system_id', models.CharField(blank=True, db_column='systemID', max_length=255, null=True)),
                ('utr_number', models.CharField(blank=True, db_column='UtrNumber', max_length=255, null=True)),
                ('version_info', models.TextField(blank=True, db_column='VersionInfo', null=True)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
