# Generated by Django 6.0.5 on 2026-05-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0005_tblpacserp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblpacserp',
            table='tblPacsErp',
        ),
    ]
