# Generated by Django 6.0.5 on 2026-05-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_alter_tblpacserp_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perpous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forWhy', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perpous',
            },
        ),
    ]
