# Generated by Django 6.0.5 on 2026-06-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0007_perpous'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblUPI',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('upiID', models.TextField(blank=True, db_column='upiID', null=True)),
                ('Remark', models.TextField(blank=True, db_column='Remark', null=True)),
                ('isActive', models.TextField(blank=True, db_column='isActive', null=True)),
            ],
            options={
                'db_table': 'tblPacsErp',
                'managed': False,
            },
        ),
    ]
