# Generated by Django 6.0.5 on 2026-07-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0008_tblupi'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('Year', models.TextField(blank=True, max_length=255, null=True, verbose_name='Year')),
                ('Version', models.TextField(blank=True, max_length=255, null=True, verbose_name='Version')),
                ('Remark', models.TextField(blank=True, max_length=255, null=True, verbose_name='Remark')),
            ],
            options={
                'db_table': 'VersionInfo',
            },
        ),
        migrations.AlterModelOptions(
            name='perpous',
            options={'verbose_name': 'Perpous', 'verbose_name_plural': 'Perpous'},
        ),
        migrations.AddField(
            model_name='perpous',
            name='ID',
            field=models.CharField(default='null', max_length=255, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perpous',
            name='fyear',
            field=models.TextField(blank=True, null=True, verbose_name='fyear'),
        ),
        migrations.AlterField(
            model_name='perpous',
            name='forWhy',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='forWhy'),
        ),
        migrations.AlterModelTable(
            name='tblupi',
            table='tblUPI',
        ),
    ]
