# Generated by Django 6.0.5 on 2026-08-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0013_tblpacserp_current_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpApiClientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_mobile', models.CharField(db_index=True, max_length=10, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('token_prefix', models.CharField(editable=False, max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['operator_mobile'],
            },
        ),
    ]
